---
- name: Install Apache
  hosts: dev
  become: true
  tasks: 
    - yum:
        name: 
          - httpd
        state: present
    - service: name=httpd state=started enabled=yes
    - raw: "echo welcome to koolkesh webpage | sudo tee /var/www/html/index.html"
    